project:
  type: website
  # output-dir: docs


website:
  title: "Eugenio Molina Navarro"
  description: "I am a scientist yeah"
  site-url: https://eugeniomolina.github.io/ugeweb/
  repo-url: https://github.com/eugeniomolina/ugeweb.git
  # favicon: logo.png
  twitter-card: true
  #   creator: "@handle"
  #   site: "@handle"
  open-graph: true
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar:
    right:
      - href: index.qmd
        text: Home
      - Projects.qmd
      - Publications.qmd
      - Docencia.qmd
      - Sobremi.qmd

#Ha quitado los iconos de la barrar de arriba porque no quedan bien en móvil

      # - icon: mastodon
      #   href: https://joinmastodon.org
      # - text: "{{< iconify fa6-brands bluesky title='BlueSky'>}}"
      #   href: https://bsky.app
      # - text: "{{< iconify fa6-brands x-twitter title='Twitter'>}}"
      #   href: https://x.com
      # - icon: github
      #   href: https://github.com
      # - icon: linkedin
      #   href: https://linkedin.com/
      # - text: "{{< iconify academicons google-scholar-square size=1.2em title='Scholar'>}}"
      #   href: https://scholar.google.com
      # - text: "{{< iconify fa6-brands orcid size=1.2em title='ORCID' >}}"
      #   href: https://orcid.org/
      - icon: rss
        href: index.xml
      # - icon: twitter
      #   href: https://twitter.com

  page-footer:
    background: light
    right: "Made with Quarto"
  # back-to-top-navigation: true


format:
  html:
    theme: flatly
    css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes



